name = "pyrecrawl-stats"
main = "src/worker.js"
compatibility_date = "2025-01-01"

# Deployed 2026-09-11 via `wrangler d1 create pyrecrawl-stats`
[[d1_databases]]
binding = "DB"
database_name = "pyrecrawl-stats"
database_id = "a61363d4-fb81-4947-bebd-5c55c6abbef5"
